server:
  port: 8081

spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: "borisov.consumer.events.UserEvent"
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

custom:
  kafka:
    enabled-java-config: true
    topics:
      user-events: user-events-topic