server:
  port: 8081

spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: borisov.consumer.event.UserEvent
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    topics:
      user-event: user-events-topic

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false

  cloud:
    openfeign:
      client:
        config:
          submit-logging:
            url: http://producer:8080/users/submit_logging