server:
  port: 8080

spring:
  application:
    name: producer

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    custom:
      enabled-java-config: true
      topic:
        user-event: user-events-topic
        partitions: 3
        replicas: 1
        configs:
          min.insync.replicas: 1
